array-methods -- Tim Woo-Sam
twoosam/c0723-code-solutions pull request #60
Opened 2023-08-22 19:05 UTC by twoosam

![image](https://github.com/twoosam/c0723-code-solutions/assets/123339845/2beb3539-8864-427e-a9f4-c8fbd81179c8)

2023-08-22 19:08 UTC, shawnkost requested changes
Few changes here Tim!

2023-08-22 19:08 UTC, shawnkost commented on array-methods/for-each.js
> +console.log('orderedValues:', orderedValues);
You should be logging each value, not logging the whole array. You also shouldn't be creating a new array

2023-08-22 19:08 UTC, shawnkost commented on array-methods/map.js
> +});
You need to make use of hte `toFixed` method here, so that there's only 2 numbers after the decimal point.

2023-08-26 22:16 UTC, RobertGardner approved these changes

2023-08-27 22:07 UTC, merged