es6-operators -- Tim Woo-Sam
twoosam/c0723-code-solutions pull request #61
Opened 2023-08-23 00:51 UTC by twoosam

![image](https://github.com/twoosam/c0723-code-solutions/assets/123339845/fad0951e-3392-4983-a598-c66cdf03a0fa)

2023-08-23 21:47 UTC, shawnkost requested changes
One change here Tim!

2023-08-23 21:47 UTC, shawnkost commented on es6-operators/main.js
> +console.log(v2 && 'v2 is truthy');
This is incorrect. The way this is structured, you are console logging regardless if the value is truthy or not. The console log should only ever run if the value is truthy.

2023-08-23 22:04 UTC, twoosam commented
![image](https://github.com/twoosam/c0723-code-solutions/assets/123339845/ab045454-71c2-4035-92d7-ff90497f47b8)

2023-08-24 17:38 UTC, shawnkost approved these changes
👍🏻

2023-08-24 17:48 UTC, merged